from __future__ import annotations

"""Integrate all sources, load the PostgreSQL star schema, and create analytical views."""

from pathlib import Path

import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

from common import PROCESSED_DIR, SQL_DIR, ensure_directories, load_settings, normalize_country


def _build_connection_url(settings: dict) -> str:
    return (
        f"postgresql+psycopg2://{settings['pg_user']}:{settings['pg_password']}"
        f"@{settings['pg_host']}:{settings['pg_port']}/{settings['pg_database']}"
    )


def _build_dim_fecha(sales: pd.DataFrame) -> pd.DataFrame:
    # Date dimension supports time-based analysis without recalculating calendar logic in BI.
    unique_dates = pd.to_datetime(sales["orderdate"]).unique()
    dates_df = pd.DataFrame({"fecha": sorted(unique_dates)})
    dates_df["fecha_id"] = range(1, len(dates_df) + 1)
    dates_df["year"] = dates_df["fecha"].dt.year
    dates_df["quarter"] = dates_df["fecha"].dt.quarter
    dates_df["month"] = dates_df["fecha"].dt.month
    dates_df["day"] = dates_df["fecha"].dt.day
    dates_df["day_of_week"] = dates_df["fecha"].dt.dayofweek
    dates_df["week_of_year"] = dates_df["fecha"].dt.isocalendar().week
    return dates_df[["fecha_id", "fecha", "year", "quarter", "month", "day", "day_of_week", "week_of_year"]]


def _build_dim_geografia(regions: pd.DataFrame, sales: pd.DataFrame) -> pd.DataFrame:
    # Build a clean one-row-per-country geography dimension before loading it into PostgreSQL.
    regions_dict = {}
    for _, row in regions.iterrows():
        key = row["pais_normalizado"]
        if key not in regions_dict:
            regions_dict[key] = row
    
    regions_clean = pd.DataFrame(list(regions_dict.values()))
    regions_clean = regions_clean.reset_index(drop=True)
    
    merged = regions_clean[
        [
            "pais_normalizado",
            "pais_oficial",
            "continente",
            "region",
            "subregion",
            "latitude",
            "longitude",
            "cca2",
            "cca3",
        ]
    ].drop_duplicates(subset=["pais_normalizado"])

    territorio_map = sales[["country_normalized", "territory"]].drop_duplicates()
    territorio_map = territorio_map.rename(columns={"country_normalized": "pais_normalizado"})

    # Keep one territory per country to avoid violating the unique constraint on country keys.
    territorio_map = territorio_map.sort_values("territory", ascending=False)
    territorio_map = territorio_map.drop_duplicates(subset=["pais_normalizado"], keep="first")
    
    merged = merged.merge(territorio_map, on="pais_normalizado", how="left")
    merged["territory"] = merged["territory"].fillna("Unknown")
    merged = merged.reset_index(drop=True)
    merged["geografia_id"] = range(1, len(merged) + 1)

    return merged[
        [
            "geografia_id",
            "pais_normalizado",
            "pais_oficial",
            "continente",
            "region",
            "subregion",
            "territory",
            "latitude",
            "longitude",
            "cca2",
            "cca3",
        ]
    ]


def _assign_customers_hybrid(
    sales: pd.DataFrame,
    customers: pd.DataFrame,
    seed: int,
) -> tuple[pd.Series, float]:
    # Prefer country-based matches, then fall back to random assignment to cover every sale line.
    rng = np.random.default_rng(seed)

    country_to_customers = (
        customers.groupby("pais_normalizado")["cliente_id"].apply(list).to_dict()
    )
    all_customers = customers["cliente_id"].tolist()

    assigned = []
    matched_by_country = 0

    for country_norm in sales["country_normalized"]:
        candidates = country_to_customers.get(country_norm, [])
        if candidates:
            matched_by_country += 1
            assigned.append(int(rng.choice(candidates)))
        else:
            assigned.append(int(rng.choice(all_customers)))

    match_rate = matched_by_country / len(sales) if len(sales) > 0 else 0.0
    return pd.Series(assigned, name="cliente_id"), match_rate


def _execute_sql_file(engine, sql_file: Path) -> None:
    # Execute schema and view DDL as a single script so the database stays consistent.
    sql_text = sql_file.read_text(encoding="utf-8")
    with engine.begin() as conn:
        conn.execute(text(sql_text))


def main() -> None:
    ensure_directories()
    settings = load_settings()

    # Load the processed staging files that were generated by the earlier pipeline steps.
    sales = pd.read_csv(PROCESSED_DIR / "sales_with_product_id.csv", parse_dates=["orderdate"])
    products = pd.read_csv(PROCESSED_DIR / "products.csv")
    customers = pd.read_csv(PROCESSED_DIR / "customers.csv")
    regions = pd.read_csv(PROCESSED_DIR / "regions.csv")

    # Normalize keys again here so the final integration step is resilient to source variation.
    sales["country_normalized"] = sales["country_normalized"].map(normalize_country)
    customers["pais_normalizado"] = customers["pais_normalizado"].map(normalize_country)
    regions["pais_normalizado"] = regions["pais_normalizado"].map(normalize_country)

    assigned_customer_ids, match_rate = _assign_customers_hybrid(
        sales=sales,
        customers=customers,
        seed=settings["seed"],
    )
    sales["cliente_id"] = assigned_customer_ids
    sales["venta_linea_id"] = np.arange(1, len(sales) + 1)

    # Derive dimension tables before building the fact table foreign keys.
    dim_fecha = _build_dim_fecha(sales)
    dim_geografia = _build_dim_geografia(regions, sales)

    fecha_map = dim_fecha.set_index("fecha")["fecha_id"].to_dict()
    sales["fecha_id"] = pd.to_datetime(sales["orderdate"]).map(fecha_map)

    geografia_map = dim_geografia.set_index("pais_normalizado")["geografia_id"].to_dict()
    sales["geografia_id"] = sales["country_normalized"].map(geografia_map)

    # Keep only the columns needed by the fact table to preserve a clean relational design.
    fact_columns = [
        "venta_linea_id",
        "ordernumber",
        "orderlinenumber",
        "status",
        "quantityordered",
        "priceeach",
        "sales",
        "dealsize",
        "fecha_id",
        "geografia_id",
        "producto_id",
        "cliente_id",
    ]
    fact_sales = sales[fact_columns].copy()

    connection_url = _build_connection_url(settings)
    engine = create_engine(connection_url)

    # Confirm the database is reachable before truncating or loading any tables.
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1;"))
    except SQLAlchemyError as exc:
        raise RuntimeError(
            "PostgreSQL connection failed. Check .env values for PG_HOST, PG_PORT, "
            "PG_DATABASE, PG_USER, and PG_PASSWORD."
        ) from exc

    # Recreate the relational objects so each run starts from a predictable state.
    _execute_sql_file(engine, SQL_DIR / "schema.sql")

    with engine.begin() as conn:
        # Truncate in reverse dependency order to avoid foreign key conflicts.
        conn.execute(text("TRUNCATE TABLE fact_ventas RESTART IDENTITY CASCADE;"))
        conn.execute(text("TRUNCATE TABLE dim_fecha RESTART IDENTITY CASCADE;"))
        conn.execute(text("TRUNCATE TABLE dim_geografia RESTART IDENTITY CASCADE;"))
        conn.execute(text("TRUNCATE TABLE dim_productos RESTART IDENTITY CASCADE;"))
        conn.execute(text("TRUNCATE TABLE dim_clientes RESTART IDENTITY CASCADE;"))

    dim_fecha.to_sql("dim_fecha", engine, if_exists="append", index=False)
    dim_geografia.to_sql("dim_geografia", engine, if_exists="append", index=False)
    products.to_sql("dim_productos", engine, if_exists="append", index=False)
    customers.to_sql("dim_clientes", engine, if_exists="append", index=False)
    fact_sales.to_sql("fact_ventas", engine, if_exists="append", index=False)

    # Create reporting views after the data is present so they can be exported immediately.
    _execute_sql_file(engine, SQL_DIR / "analytics_views.sql")

    integration_report = pd.DataFrame(
        [
            {
                "rows_fact_ventas": len(fact_sales),
                "rows_dim_fecha": len(dim_fecha),
                "rows_dim_geografia": len(dim_geografia),
                "rows_dim_productos": len(products),
                "rows_dim_clientes": len(customers),
                "customer_match_rate_by_country": round(match_rate, 4),
                "fallback_rate": round(1.0 - match_rate, 4),
            }
        ]
    )
    report_path = PROCESSED_DIR / "integration_report.csv"
    integration_report.to_csv(report_path, index=False)

    print("[OK] PostgreSQL integration completed.")
    print(f"[OK] Integration report saved to: {report_path}")


if __name__ == "__main__":
    main()
